version: "3"
services:
  socks-server:
    restart: always
    container_name: socks-server
    image: colachen/socks-server
    ports:
      - "443:443"
      - "2000:2000"
    volumes:
      - ${PWD}/config/supervisord4.conf:/etc/supervisord.conf
      - ${PWD}/config/trojan-go:/etc/trojan-go
    environment:
      - PASSWORD=PASSWORD
      - SERVER=1.2.3.4
